{
  try {
    e(t,message,args);
  }
 catch (  Exception e) {
    e("failed to log error" + message);
  }
}
