{
  try {
    e(message,args);
  }
 catch (  Exception e) {
    e("failed to log error: " + message);
  }
}
